<a href="https://colab.research.google.com/github/AnishShrestha09/pandas/blob/main/pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Convert full names into lowercase usernames by joining the first and last names

names = [
"Aman Sharma",
"Riya Verma",
"Karan Patel hello"
]

# with a dot.

In [ ]:
for name in names:
  arr1 = name.split(" ")

  # for a in range(len(arr)-1):
  for arr in arr1:
    print(arr.lower(),"")
    print()

aman

sharma

riya

verma

karan

patel

hello

In [ ]:
# Create a new list containing each value only once, preserving the order of its first appearance.

numbers = [4, 2, 4, 7, 2, 9, 7, 10]
howmany = []


for num in numbers:
  if num not in howmany:
      howmany.append(num)

print(howmany)

[4, 2, 7, 9, 10]

In [ ]:
# Given a list of integers, determine whether the list is sorted in ascending order.

# Do not use sort() or sorted().

# Input: [10, 20, 30, 40]
# Output: Sorted

# Input: [10, 30, 20, 40]
# Output: Not Sorted

In [ ]:
Input =  [10, 30, 20, 40]

num1 = Input[0]
flag = True

for input in Input[1:]:
  if input > num1 :
    num1 = input
  else:
    flag= False
    break

print(flag)

False

In [ ]:
# Student name
# Student ID
# Branch
# Attendance percentage
# Examination marks
# Study hours
# Placement status

In [ ]:
# Pandas can be used to perform the following:

# Organizing data into rows and columns.
# Reading data from CSV and Excel files.
# Selecting specific rows and columns.
# Filtering records based on conditions.
# Handling missing values.
# Cleaning inconsistent data.
# Calculating statistics.
# Grouping and summarizing information.
# Combining datasets.
# Preparing data for visualization and machine learning.

In [ ]:
student_names = ["Amit", "Priya", "Rahul", "Sneha"]
marks = [85, 92, 67, 78]

print(student_names)
print(marks)

['Amit', 'Priya', 'Rahul', 'Sneha']
[85, 92, 67, 78]

In [ ]:
sum = sum(marks)
length = len(marks)

avg = sum/length
print(avg)

80.5

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pd.__version__

'2.2.3'

In [ ]:
dictionary = {
  "names":["mll","mllmg","mllbbs"],
  "marks" : [100,200,300]
}

students = pd.DataFrame(dictionary)

In [ ]:
students

    names  marks
0     mll    100
1   mllmg    200
2  mllbbs    300

In [ ]:
# series

marks = pd.Series([1,2,3,4,5])

In [ ]:
marks

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
print(np.average(marks))
print(np.min(marks))
print(np.max(marks))

3.0
1
5

In [ ]:
temperatures = pd.Series([30, 32, 31, 29, 35, 34, 33])

In [ ]:
np.max(temperatures)
np.min(temperatures)
np.mean(temperatures)

np.float64(32.0)

In [ ]:
len(temperatures)

7

In [ ]:
pd.Series([1,2,3.3,4,5,"anish"])

0        1
1        2
2      3.3
3        4
4        5
5    anish
dtype: object

In [ ]:
months = pd.Series([ 1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9, 10, 11, 12])
print(months)

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
dtype: int64

In [ ]:
sales = pd.Series([1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9, 10, 11, 12])
print(sales)

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
dtype: int64

In [ ]:
salesmonth = pd.Series([1000 , 2000 , 3000 ],
                          index= ["jan","feb","march"])

In [ ]:
print(salesmonth)

jan      1000
feb      2000
march    3000
dtype: int64

In [ ]:
# how to access 2

salesmonth["feb"]
print(salesmonth)

jan      1000
feb      2000
march    3000
dtype: int64

In [ ]:
# what % of sales came from Jan?

total = salesmonth.sum()

janperc = salesmonth["jan"]/total * 100

print(np.round(janperc))

17.0

In [ ]:
# Seires:
# index         values
# subjects .== > .marks

In [ ]:
pd.Series([70,80,90,100],
          index = ["maths","science","bio","eco"])

maths       70
science     80
bio         90
eco        100
dtype: int64

In [ ]:
s = {
    "math":100,
     "science":100,
     "sql":100
}

pd.Series(s)

math       100
science    100
sql        100
dtype: int64

In [ ]:
#Create a Pandas series from a Numpy array.


no = np.array([1,1,23,4,55])

no2 = pd.Series(no)
print(no2+ 5)

0     6
1     6
2    28
3     9
4    60
dtype: int64

In [ ]:
#write a code to create a numpy array of marks (out of 100)
#  and then assign 10 bonus marks to each.

marks = np.arange(90,100)
np.minimum(marks+10,100)

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])