<a href="https://colab.research.google.com/github/AnishShrestha09/pandas/blob/main/pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = {
"Student": ["Amit", "Priya", "Rahul", "Sneha", "Karan",
"Neha", "Rohit", "Pooja", "Arjun", "Meera"],
"Age": [18, 19, 18, 20, 19, 18, 21, 19, 20, 18],
"Marks": [78, 92, 65, 88, 45, 95, 56, 72, 81, 69],
"Attendance": [85, 95, 70, 90, 60, 98, 75, 82, 88, 68],
"Branch": ["CSE", "ECE", "CSE", "IT", "ME","CSE", "ECE", "IT", "ME", "CSE"]
}
students = pd.DataFrame(data)

In [ ]:
students

  Student  Age  Marks  Attendance Branch
0    Amit   18     78          85    CSE
1   Priya   19     92          95    ECE
2   Rahul   18     65          70    CSE
3   Sneha   20     88          90     IT
4   Karan   19     45          60     ME
5    Neha   18     95          98    CSE
6   Rohit   21     56          75    ECE
7   Pooja   19     72          82     IT
8   Arjun   20     81          88     ME
9   Meera   18     69          68    CSE

In [ ]:
# limit like in sql
students.head(3)

  Student  Age  Marks  Attendance Branch
0    Amit   18     78          85    CSE
1   Priya   19     92          95    ECE
2   Rahul   18     65          70    CSE

In [ ]:
students.tail()

  Student  Age  Marks  Attendance Branch
5    Neha   18     95          98    CSE
6   Rohit   21     56          75    ECE
7   Pooja   19     72          82     IT
8   Arjun   20     81          88     ME
9   Meera   18     69          68    CSE

In [ ]:
# get the last 3 rows

students.tail(3)

  Student  Age  Marks  Attendance Branch
7   Pooja   19     72          82     IT
8   Arjun   20     81          88     ME
9   Meera   18     69          68    CSE

In [ ]:
students

  Student  Age  Marks  Attendance Branch
0    Amit   18     78          85    CSE
1   Priya   19     92          95    ECE
2   Rahul   18     65          70    CSE
3   Sneha   20     88          90     IT
4   Karan   19     45          60     ME
5    Neha   18     95          98    CSE
6   Rohit   21     56          75    ECE
7   Pooja   19     72          82     IT
8   Arjun   20     81          88     ME
9   Meera   18     69          68    CSE

In [ ]:
# get the random row
students.sample()

  Student  Age  Marks  Attendance Branch
7   Pooja   19     72          82     IT

In [ ]:
students.sample(3)

  Student  Age  Marks  Attendance Branch
9   Meera   18     69          68    CSE
7   Pooja   19     72          82     IT
0    Amit   18     78          85    CSE

In [ ]:
students.sample(3)

  Student  Age  Marks  Attendance Branch
5    Neha   18     95          98    CSE
3   Sneha   20     88          90     IT
4   Karan   19     45          60     ME

In [ ]:
students.sample(3,random_state=42)

  Student  Age  Marks  Attendance Branch
8   Arjun   20     81          88     ME
1   Priya   19     92          95    ECE
5    Neha   18     95          98    CSE

In [ ]:
students.sample(3,random_state=42)

  Student  Age  Marks  Attendance Branch
8   Arjun   20     81          88     ME
1   Priya   19     92          95    ECE
5    Neha   18     95          98    CSE

In [ ]:
large_df = pd.DataFrame({
"Employee_ID": range(1001, 1021),
"Salary": [
25000, 30000, 28000, 45000, 50000,
32000, 38000, 41000, 29000, 60000,
35000, 48000, 52000, 27000, 39000,
43000, 31000, 55000, 36000, 47000
]
})

In [ ]:
large_df

    Employee_ID  Salary
0          1001   25000
1          1002   30000
2          1003   28000
3          1004   45000
4          1005   50000
5          1006   32000
6          1007   38000
7          1008   41000
8          1009   29000
9          1010   60000
10         1011   35000
11         1012   48000
12         1013   52000
13         1014   27000
14         1015   39000
15         1016   43000
16         1017   31000
17         1018   55000
18         1019   36000
19         1020   47000

In [ ]:
large_df.sample(5,random_state=42)

    Employee_ID  Salary
0          1001   25000
17         1018   55000
15         1016   43000
1          1002   30000
8          1009   29000

In [ ]:
large_df.sample(5,random_state=42)

    Employee_ID  Salary
0          1001   25000
17         1018   55000
15         1016   43000
1          1002   30000
8          1009   29000

In [ ]:
large_df.shape

(20, 2)

In [ ]:
row, col = large_df.shape
print(row)
print(col)

20
2

In [ ]:
row, col = large_df.shape

size = row * col
print(size)

40

In [ ]:
# check whether the dataset has records

In [ ]:
large_df.empty

False

In [ ]:
if(large_df.shape[0]>0):
    print("we have records")

we have records

In [ ]:
# create a empty dataframe

df = pd.DataFrame()

In [ ]:
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
df.shape

(0, 0)

In [ ]:
#write a code to get all the column names

In [ ]:
large_df.columns

Index(['Employee_ID', 'Salary'], dtype='object')

In [ ]:
large_df

    Employee_ID  Salary
0          1001   25000
1          1002   30000
2          1003   28000
3          1004   45000
4          1005   50000
5          1006   32000
6          1007   38000
7          1008   41000
8          1009   29000
9          1010   60000
10         1011   35000
11         1012   48000
12         1013   52000
13         1014   27000
14         1015   39000
15         1016   43000
16         1017   31000
17         1018   55000
18         1019   36000
19         1020   47000

In [ ]:
list(large_df.columns)

['Employee_ID', 'Salary']

In [ ]:
# check a specific column exists in a dataframe
if "Salary" in list(large_df.columns):
  print("it exists")
else:
  print("doesnot exist")

it exists

In [ ]:
#  change the name of columns

large_df.columns= ["ID","Salary"]

In [ ]:
large_df

      ID  Salary
0   1001   25000
1   1002   30000
2   1003   28000
3   1004   45000
4   1005   50000
5   1006   32000
6   1007   38000
7   1008   41000
8   1009   29000
9   1010   60000
10  1011   35000
11  1012   48000
12  1013   52000
13  1014   27000
14  1015   39000
15  1016   43000
16  1017   31000
17  1018   55000
18  1019   36000
19  1020   47000

In [ ]:
# Find the Product of All Elements Except the Current Element

# Problem statement: Create a result array in which each position contains
# the product of all the other array elements, without dividing by the current element.

# example : [1,2,3,4]
# output: []

In [2]:
input = [1,2,3,4]
multi=[]

num = len(input)
start = -1
mul = 1
for j in input:
  start +=1
  mul = 1
  for i in range(num):
    if(i != start):
      mul *= input[i]


  multi.append(mul)
print(multi)

[24, 12, 8, 6]

In [ ]:
# Left Rotate an Array by One Position

# Problem statement:
# Given an array, rotate all elements one position to the left.
# The first element should move to the last position.

# Example: [10, 20, 30, 40, 50]
# Output: [20, 30 , 40 , 50 ,10 ]

In [4]:
input = [10, 20, 30, 40, 50]
output = []


if(len(input)>1):
  for i in input[1:] :
    output.append(i)

output.append(input[0])

print(output)

[50]

In [7]:
# Right Rotate an Array by K Positions

# Problem statement: Rotate an array to the right by k positions.


Example = [1, 2, 3, 4, 5]
Output = []

Output = Example[3:] + Example[:3]
print(Output)

[4, 5, 1, 2, 3]

In [ ]:
# Find the Union of Two Arrays

# Problem statement: Print every distinct element that appears in either of two arrays.
# Do not print duplicates.
Example = [1,2, 3, 4, 5]
Example2 = [1, 2, 3, 4, 5,6]
Example3= []

for i in Example:
  if i in Example2:
    Example3.append(i)
  else:
    Example3.append(i)