<a href="https://colab.research.google.com/github/AnishShrestha09/pandas/blob/main/pandas4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = {
"Student_ID": [101, 102, 103, 104, 105, 106, 107, 108],
"Name": ["Amit", "Priya", "Rahul", "Sneha",
"Karan", "Neha", "Rohit", "Pooja"],
"Branch": ["CSE", "ECE", "CSE", "IT",
"ME", "CSE", "ECE", "IT"],
"Age": [18, 19, 18, 20, 19, 18, 21, 19],
"Marks": [78, 92, 65, 88, 45, 95, 56, 72],
"Attendance": [85, 95, 70, 90, 60, 98, 75, 82]
}

df = pd.DataFrame(data)

In [2]:
df

   Student_ID   Name Branch  Age  Marks  Attendance
0         101   Amit    CSE   18     78          85
1         102  Priya    ECE   19     92          95
2         103  Rahul    CSE   18     65          70
3         104  Sneha     IT   20     88          90
4         105  Karan     ME   19     45          60
5         106   Neha    CSE   18     95          98
6         107  Rohit    ECE   21     56          75
7         108  Pooja     IT   19     72          82

In [4]:
# check the null and the dtypes

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  8 non-null      int64
 1   Name        8 non-null      object
 2   Branch      8 non-null      object
 3   Age         8 non-null      int64
 4   Marks       8 non-null      int64
 5   Attendance  8 non-null      int64
dtypes: int64(4), object(2)
memory usage: 516.0+ bytes

In [7]:
# access the specific column
names = df["Name"]
names

0     Amit
1    Priya
2    Rahul
3    Sneha
4    Karan
5     Neha
6    Rohit
7    Pooja
Name: Name, dtype: object

In [13]:
# access the last and first name

print(names.head(1))
print(names.tail(1))

0    Amit
Name: Name, dtype: object
7    Pooja
Name: Name, dtype: object

In [14]:
# access the last and first name
names.iloc[0]

'Amit'

In [15]:
names.iloc[-1]

'Pooja'

In [16]:
names[0]

'Amit'

In [17]:
names[7]

'Pooja'

In [19]:
# access the name
df.Name # should not prefer this

0     Amit
1    Priya
2    Rahul
3    Sneha
4    Karan
5     Neha
6    Rohit
7    Pooja
Name: Name, dtype: object

In [20]:
#  access the numltiple columns

df[["Name","Age"]]

    Name  Age
0   Amit   18
1  Priya   19
2  Rahul   18
3  Sneha   20
4  Karan   19
5   Neha   18
6  Rohit   21
7  Pooja   19

In [21]:
# Create a new dataframe with only the Name, Age and Branch columns in it

newdf = df[["Name","Age","Branch"]]

In [22]:
newdf

    Name  Age Branch
0   Amit   18    CSE
1  Priya   19    ECE
2  Rahul   18    CSE
3  Sneha   20     IT
4  Karan   19     ME
5   Neha   18    CSE
6  Rohit   21    ECE
7  Pooja   19     IT

In [23]:
type(df["Name"])

pandas.core.series.Series

In [24]:
type(df[["Name"]])

pandas.core.frame.DataFrame

In [ ]:
# Find the Frequency of Every Element

# Print each unique element along with its frequency.
# Input: 10 20 10 30 20 10
# output :
        # 10 3
#         20 2
#         30 1

In [25]:
Input= [10 ,20, 10, 30, 20, 10]
output = {}

for i in Input:
  if i  not in output:
    output[i] = 1
  else:
    output[i]+=1


print(output)

{10: 3, 20: 2, 30: 1}

In [ ]:
# Find the First Repeating Element

# Find the first element in the array that appears more than once.

# Input:
# 5 7 3 7 2 3

# Output: 7

In [28]:
Input= [5, 7, 3, 7, 2, 3]
output= []

for i in Input:
  if i not in output:
    output.append(i)
  else:
    print(i)
    break

7

In [ ]:
# Find the First Non-Repeating Element

# Find the first element whose frequency is exactly 1.

# Input:
# 4 5 4 6 5 7 6

Output: 7

In [37]:
Input=[ 4, 5, 4, 6, 5, 7, 6]
output = {}

for i in Input:
  if i  not in output:
    output[i] = 1
  else:
    output[i]+=1


for key in output:
  if(output[key]==1):
    print(key)
    break

7

In [ ]:
### Check Whether the Array is Sorted

Determine whether an array is sorted in ascending order.

**Input:**
`10 20 25 30 45`

In [41]:
Input = [10, 20, 25, 30, 45,30]
flag = True
for i in range(0,len(Input)-1):
  if(Input[i]>Input[i+1]):
    flag = False


print(flag)

False

In [ ]:
# Find the Largest Difference Between Two Elements

# Find the maximum difference between two elements
# where the larger element occurs after the smaller element.

# Input:
# 7 1 5 3 6 4

# Output:
# 5