<a href="https://colab.research.google.com/github/AnishShrestha09/pandas/blob/main/pandas10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Remove all occurrences of a chosen pattern

# Problem statement: Given a string and a pattern,
# remove every occurrence of that pattern while preserving the order of the remaining characters.

# Example: String = "programming", character = "mi"
# output: "programng"

In [5]:
String = "programming"
character = "mi"


String.replace("mi","")

'programng'

In [ ]:
# Find the ASCII value of each character

# Problem statement:
# Given a string containing basic ASCII characters,
# print each character and its numeric ASCII value.

# Example: "Cat"
# Output:

In [6]:
Example= "Cat"

for i in Example:
  print(i, ord(i))

C 67
a 97
t 116

In [ ]:
# Remove

# all occurrences of a chosen character


# Problem statement: Given a string and a character,
# remove every occurrence of that character while preserving the order of the remaining characters.


# Example: String = "programming", character = 'm'
# output:

In [7]:
String = "programming"
character = 'm'

String.replace('m','')

'prograing'

In [ ]:
# Count the number of words in a sentence

# Problem statement:
# Count the words in a sentence.
# Words are separated by one or more spaces, and leading or trailing spaces should not affect the answer

Example =  " Learn DSA today"
Output =  3

In [14]:
Example2=  " Learn DSA today"
# Example2 = Example.strip()


arr = Example2.split()
len(arr)

3

In [ ]:
# from a string

# Problem statement: Create a new string by removing every ordinary space character from the input.

# Output: "Iloveprogramming"

# Remove all spaces

In [15]:
Example =  "I love programming"


Example.replace(" ","")

'Iloveprogramming'

In [1]:
import pandas as pd
import numpy as np

sales = pd.DataFrame( {
"Product": ["Laptop","Mouse", "Monitor", "Keyboard", "Printer"],
"Quantity": [5, 20, 4, 10, 3],
"Unit_Price": [50000, 800, 12000, 1500, 18000],
"Cost": [220000, 10000, 40000, 10000, 45000]
})

In [ ]:
sales['Revenue'] = sales['Quantity'] * sales['Unit_Price']

In [ ]:
sales

    Product  Quantity  Unit_Price    Cost  Revenue
0    Laptop         5       50000  220000   250000
1     Mouse        20         800   10000    16000
2   Monitor         4       12000   40000    48000
3  Keyboard        10        1500   10000    15000
4   Printer         3       18000   45000    54000

In [ ]:
#  find the profit

sales['profit'] = sales['Revenue'] - sales['Cost']

In [ ]:
sales["sales_cat"] = np.where(
   sales['profit']> 10000,
    "highProfit",
    "lowProfit"
)

In [ ]:
sales

    Product  Quantity  Unit_Price    Cost  Revenue  profit   sales_cat
0    Laptop         5       50000  220000   250000   30000  highProfit
1     Mouse        20         800   10000    16000    6000   lowProfit
2   Monitor         4       12000   40000    48000    8000   lowProfit
3  Keyboard        10        1500   10000    15000    5000   lowProfit
4   Printer         3       18000   45000    54000    9000   lowProfit

In [ ]:
students = pd.DataFrame({
"Name": ["Amit", "Priya", "Rahul", "Sneha", "Karan"],
"Python": [85, 95, 45, 70, 55],
"SQL": [80, 90, 50, 65, 60],
"Statistics": [90, 92, 40, 75, 50]
})

In [ ]:
students

    Name  Python  SQL  Statistics
0   Amit      85   80          90
1  Priya      95   90          92
2  Rahul      45   50          40
3  Sneha      70   65          75
4  Karan      55   60          50

In [ ]:
# Problem: Calculate total marks.and percentage for three subjects.
# Assign grade .A for .a.percentage .of at least 80,
# B.for.at least.60.but.below.80, and .C.otherwise.

In [ ]:
students["total_marks"] = students[["Statistics","SQL","Python"]].sum(axis = 1)

In [ ]:
students

    Name  Python  SQL  Statistics  total_marks
0   Amit      85   80          90          255
1  Priya      95   90          92          277
2  Rahul      45   50          40          135
3  Sneha      70   65          75          210
4  Karan      55   60          50          165

In [ ]:
# Assign grade A for a percentage of at least 80
# B.for.at least.60.but.below.80, and .C.otherwise.

students["percentage"] = np.round(students["total_marks"]/3,2)

students["Grade"] = np.where(
    students["percentage"]> 80,
    "A",
    np.where(
         (students["percentage"]>= 60) & (students["percentage"]<80),
    "B",
      "C"
    )
)

In [ ]:
students

    Name  Python  SQL  Statistics  total_marks  percentage Grade
0   Amit      85   80          90          255       85.00     A
1  Priya      95   90          92          277       92.33     A
2  Rahul      45   50          40          135       45.00     C
3  Sneha      70   65          75          210       70.00     B
4  Karan      55   60          50          165       55.00     C

In [ ]:
# Problem: Increase all product prices by 8%, rename Unit_Price to Updated_Price,
# and delete Supplier_Contact.

products = pd.DataFrame ({
"Product": ["Laptop", "Mouse", "Monitor", "Keyboard"],
"Unit_Price": [50000, 800, 12000, 1500],
"Supplier_Contact": [
"9876500001", "9876500002", "9876500003", "9876500004"]
})

In [ ]:
products

    Product  Unit_Price Supplier_Contact
0    Laptop       50000       9876500001
1     Mouse         800       9876500002
2   Monitor       12000       9876500003
3  Keyboard        1500       9876500004

In [ ]:
# Problem: Increase all product prices by 8%, rename Unit_Price to Updated_Price,
# and delete Supplier_Contact.

products["Unit_Price"] = 1.08 * products["Unit_Price"]
products

    Product  Unit_Price Supplier_Contact
0    Laptop     54000.0       9876500001
1     Mouse       864.0       9876500002
2   Monitor     12960.0       9876500003
3  Keyboard      1620.0       9876500004

In [ ]:
products

    Product  Unit_Price Supplier_Contact
0    Laptop     54000.0       9876500001
1     Mouse       864.0       9876500002
2   Monitor     12960.0       9876500003
3  Keyboard      1620.0       9876500004

In [ ]:
products = products.rename(columns = {"Unit_Price":"Updated_Price"})

In [ ]:
products

    Product  Updated_Price Supplier_Contact
0    Laptop        54000.0       9876500001
1     Mouse          864.0       9876500002
2   Monitor        12960.0       9876500003
3  Keyboard         1620.0       9876500004

In [ ]:
#  remove the Supplier_Contact columns the dataframe

In [ ]:
products.drop(columns = ["Supplier_Contact"])

    Product  Updated_Price
0    Laptop        54000.0
1     Mouse          864.0
2   Monitor        12960.0
3  Keyboard         1620.0

In [ ]:
products

    Product  Updated_Price Supplier_Contact
0    Laptop        54000.0       9876500001
1     Mouse          864.0       9876500002
2   Monitor        12960.0       9876500003
3  Keyboard         1620.0       9876500004

In [ ]:
#save this updated dataframe as a csv file.

products.to_csv("products.csv",index = False)