<a href="https://colab.research.google.com/github/AnishShrestha09/pandas/blob/main/pandas7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": [
        "Amit", "Priya", "Rahul", "Sneha", "Karan",
        "Neha", "Rohit", "Pooja", "Anjali", "Vikas"
    ],
    "Branch": [
        "CSE", "ECE", "CSE", "IT", "ME",
        "CSE", "ECE", "IT", "EEE", "CSE"
    ],
    "Marks": [82, 91, 68, 88, 76, 95, 79, 72, 85, 74],
    "Attendance": [85, 92, 78, 90, 88, 96, 83, 95, 86, 75],
    "Backlogs": [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    "Placement_Training": [
        "Yes", "Yes", "No", "Yes", "Yes",
        "Yes", "No", "Yes", "Yes", "No"
    ]
}

df = pd.DataFrame(data)

print(df)

   Student_ID    Name Branch  Marks  Attendance  Backlogs Placement_Training
0         101    Amit    CSE     82          85         0                Yes
1         102   Priya    ECE     91          92         0                Yes
2         103   Rahul    CSE     68          78         1                 No
3         104   Sneha     IT     88          90         0                Yes
4         105   Karan     ME     76          88         0                Yes
5         106    Neha    CSE     95          96         0                Yes
6         107   Rohit    ECE     79          83         0                 No
7         108   Pooja     IT     72          95         0                Yes
8         109  Anjali    EEE     85          86         0                Yes
9         110   Vikas    CSE     74          75         0                 No

In [5]:
# Display the first five and last three records

df[:5]

   Student_ID   Name Branch  Marks  Attendance  Backlogs Placement_Training
0         101   Amit    CSE     82          85         0                Yes
1         102  Priya    ECE     91          92         0                Yes
2         103  Rahul    CSE     68          78         1                 No
3         104  Sneha     IT     88          90         0                Yes
4         105  Karan     ME     76          88         0                Yes

In [4]:
df[-3:]

   Student_ID    Name Branch  Marks  Attendance  Backlogs Placement_Training
7         108   Pooja     IT     72          95         0                Yes
8         109  Anjali    EEE     85          86         0                Yes
9         110   Vikas    CSE     74          75         0                 No

In [6]:
# Inspect the dataset's shape, column names, data types, and summary statistics.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          10 non-null     int64
 1   Name                10 non-null     object
 2   Branch              10 non-null     object
 3   Marks               10 non-null     int64
 4   Attendance          10 non-null     int64
 5   Backlogs            10 non-null     int64
 6   Placement_Training  10 non-null     object
dtypes: int64(4), object(3)
memory usage: 692.0+ bytes

In [7]:
# Select only the student name, branch, marks, and attendance columns.

df[["Name","Branch","Marks","Attendance"]]

     Name Branch  Marks  Attendance
0    Amit    CSE     82          85
1   Priya    ECE     91          92
2   Rahul    CSE     68          78
3   Sneha     IT     88          90
4   Karan     ME     76          88
5    Neha    CSE     95          96
6   Rohit    ECE     79          83
7   Pooja     IT     72          95
8  Anjali    EEE     85          86
9   Vikas    CSE     74          75

In [8]:
# Identify students with marks of at least 75 and attendance of at least 80%.
df[(df["Marks"]>=75)&(df["Marks"]>=80)]

   Student_ID    Name Branch  Marks  Attendance  Backlogs Placement_Training
0         101    Amit    CSE     82          85         0                Yes
1         102   Priya    ECE     91          92         0                Yes
3         104   Sneha     IT     88          90         0                Yes
5         106    Neha    CSE     95          96         0                Yes
8         109  Anjali    EEE     85          86         0                Yes

In [ ]:
# Restrict the results to students from CSE, IT, or ECE.
# Exclude students with pending backlogs.

In [10]:
df[df["Branch"].isin(["CSE","IT","CSE"])]

   Student_ID   Name Branch  Marks  Attendance  Backlogs Placement_Training
0         101   Amit    CSE     82          85         0                Yes
2         103  Rahul    CSE     68          78         1                 No
3         104  Sneha     IT     88          90         0                Yes
5         106   Neha    CSE     95          96         0                Yes
7         108  Pooja     IT     72          95         0                Yes
9         110  Vikas    CSE     74          75         0                 No

In [11]:
import pandas as pd

students = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": [
        "Amit", "Priya", "Rahul", "Sneha", "Karan",
        "Neha", "Rohit", "Pooja", "Anjali", "Vikas"
    ],
    "Branch": [
        "CSE", "ECE", "CSE", "IT", "ME",
        "CSE", "ECE", "IT", "EEE", "CSE"
    ],
    "Marks": [82, 91, 68, 88, 76, 95, 79, 72, 85, 74],
    "Attendance": [85, 92, 78, 90, 88, 96, 83, 95, 86, 75],
    "Backlogs": [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
    "Placement_Training": [
        "Yes", "Yes", "No", "Yes", "Yes",
        "Yes", "No", "Yes", "Yes", "No"
    ]
})

students

   Student_ID    Name Branch  Marks  Attendance  Backlogs Placement_Training
0         101    Amit    CSE     82          85         0                Yes
1         102   Priya    ECE     91          92         0                Yes
2         103   Rahul    CSE     68          78         1                 No
3         104   Sneha     IT     88          90         0                Yes
4         105   Karan     ME     76          88         0                Yes
5         106    Neha    CSE     95          96         0                Yes
6         107   Rohit    ECE     79          83         0                 No
7         108   Pooja     IT     72          95         0                Yes
8         109  Anjali    EEE     85          86         0                Yes
9         110   Vikas    CSE     74          75         0                 No

In [13]:
students[students["Backlogs"]==0]

   Student_ID    Name Branch  Marks  Attendance  Backlogs Placement_Training
0         101    Amit    CSE     82          85         0                Yes
1         102   Priya    ECE     91          92         0                Yes
3         104   Sneha     IT     88          90         0                Yes
4         105   Karan     ME     76          88         0                Yes
5         106    Neha    CSE     95          96         0                Yes
6         107   Rohit    ECE     79          83         0                 No
7         108   Pooja     IT     72          95         0                Yes
8         109  Anjali    EEE     85          86         0                Yes
9         110   Vikas    CSE     74          75         0                 No

In [17]:
# Display the first three eligible students using position-based indexing.


eligible = students[students["Placement_Training"]=="Yes"]
eligible.head(3)

   Student_ID   Name Branch  Marks  Attendance  Backlogs Placement_Training
0         101   Amit    CSE     82          85         0                Yes
1         102  Priya    ECE     91          92         0                Yes
3         104  Sneha     IT     88          90         0                Yes

In [19]:
import numpy as np

In [21]:
# Calculate the average marks of eligible students.
meanmarks = np.mean(eligible["Marks"])


# find the students who are above this avg marks.

students[students["Marks"]>meanmarks]

   Student_ID    Name Branch  Marks  Attendance  Backlogs Placement_Training
1         102   Priya    ECE     91          92         0                Yes
3         104   Sneha     IT     88          90         0                Yes
5         106    Neha    CSE     95          96         0                Yes
8         109  Anjali    EEE     85          86         0                Yes

In [22]:
#  save the data into csv file
eligible.to_csv("data.csv")