<a href="https://colab.research.google.com/github/AnishShrestha09/pandas/blob/main/pandas5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
"Student_ID": [101, 102, 103, 104, 105, 106, 107, 108],
"Name": ["Amit", "Priya", "Rahul", "Sneha",
"Karan", "Neha", "Rohit", "Pooja"],
"Age": [18, 19, 18, 20, 19, 18, 21, 19],
"Branch": ["CSE", "ECE", "CSE", "IT",
"ME", "CSE", "ECE", "IT"],
"Marks": [78, 92, 65, 88, 45, 95, 56, 72],
"Attendance": [85, 95, 70, 90, 60, 98, 75, 82]

})

In [ ]:
df

   Student_ID   Name  Age Branch  Marks  Attendance
0         101   Amit   18    CSE     78          85
1         102  Priya   19    ECE     92          95
2         103  Rahul   18    CSE     65          70
3         104  Sneha   20     IT     88          90
4         105  Karan   19     ME     45          60
5         106   Neha   18    CSE     95          98
6         107  Rohit   21    ECE     56          75
7         108  Pooja   19     IT     72          82

In [ ]:
# loc => helps to access using row labels and column labels

In [ ]:
df.loc[1]

Student_ID      102
Name          Priya
Age              19
Branch          ECE
Marks            92
Attendance       95
Name: 1, dtype: object

In [ ]:
df.loc[7]

Student_ID      108
Name          Pooja
Age              19
Branch           IT
Marks            72
Attendance       82
Name: 7, dtype: object

In [ ]:
#  1 3 4 student info

df.loc[[0,2,3]]

   Student_ID   Name  Age Branch  Marks  Attendance
0         101   Amit   18    CSE     78          85
2         103  Rahul   18    CSE     65          70
3         104  Sneha   20     IT     88          90

In [ ]:
#  row  2 to 5

df.loc[1:4]

   Student_ID   Name  Age Branch  Marks  Attendance
1         102  Priya   19    ECE     92          95
2         103  Rahul   18    CSE     65          70
3         104  Sneha   20     IT     88          90
4         105  Karan   19     ME     45          60

In [ ]:
# access age column using loc
df.loc[:,"Age"]

0    18
1    19
2    18
3    20
4    19
5    18
6    21
7    19
Name: Age, dtype: int64

In [ ]:
df.loc[:,["Age","Marks","Branch"]]

   Age  Marks Branch
0   18     78    CSE
1   19     92    ECE
2   18     65    CSE
3   20     88     IT
4   19     45     ME
5   18     95    CSE
6   21     56    ECE
7   19     72     IT

In [ ]:
# student 2nd to 6th -- > Age, Marks

df.loc[1:5,["Age","Marks"]]

   Age  Marks
1   19     92
2   18     65
3   20     88
4   19     45
5   18     95

In [ ]:
# stduents 3rd and 5th -- > Age, Branch

df.loc[[2,4],["Age","Branch"]]

   Age Branch
2   18    CSE
4   19     ME

In [ ]:
# iloc =>  access using indexing

In [ ]:
df.iloc[1]

Student_ID      102
Name          Priya
Age              19
Branch          ECE
Marks            92
Attendance       95
Name: 1, dtype: object

In [ ]:
df.iloc[-1]
df.loc[7]

Student_ID      108
Name          Pooja
Age              19
Branch           IT
Marks            72
Attendance       82
Name: 7, dtype: object

In [4]:
# find the smallest absolute difference between an element of the first array and an element of the second.

# Example: # Output: 1
A = [1, 4, 8, 10]
B = [2, 5,9,12]

smallest =float('inf')
for i in A:
  for j in B:
    diff = i - j
    if diff < 0:
      diff *= -1
    if smallest > diff:
      smallest = diff

print(smallest)

1