<a href="https://colab.research.google.com/github/AnishShrestha09/pandas/blob/main/pandas8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
chr(65)

'A'

In [5]:
ord("A")

65

In [6]:
ord("a")

97

In [ ]:
# Check whether two strings are anagrams

# Problem:
# Two strings are anagrams if they contain the same characters with the same frequencies, regardless of order.
# Assume the strings contain lowercase English letters.

# Example: Input: listen, silent|
# Output: True

In [27]:
example1 = "aab"
example2 = "abb"

arr=[]
arr2 = []
anagram = True


for i in example1:
  arr.append(ord(i))

for j in example2:
  arr2.append(ord(j))



if len(arr)!=len(arr2):
  anagram= False
  print("not anagram")

else:
  for i in arr.copy():
    if i in arr2:
      arr.remove(i)
      arr2.remove(i)



  if arr == arr2:
    print("anagram")
  else:
    print("not anagram")

not anagram

In [ ]:
# Find the first non-repeating character in a string


# Problem:
# Find the first character that appears exactly once.
# If every character repeats, print None. Assume lowercase English letters.

# Example: Input: swiss
# Output:

In [13]:
Input = "swiss"
Dictionary = {}


for i in Input:
  if i not in Dictionary:
    Dictionary[i] = 1
  else:
    Dictionary[i] +=1

for i in Dictionary:
  if(Dictionary[i]==1):
    print(i)
    break

w

In [ ]:
# Calculate the average of elements greater than a given value

# Problem statement:
# Given an array and a number K, calculate the average of all elements strictly greater than K.
# If no element qualifies, print No elements.
# MW

# Example: Array = [10, 25, 30, 15, 40], K = 20
# OutputE

In [ ]:
# Find the difference
# between the sum of even and odd elements

# Problem statement:
# Print the absolute difference between the two sums.

# [2, 7, 4, 9, 6]

# Calculate the sum of even-valued elements and the sum of odd-valued elements.

# Example:
# Output:

In [23]:
Example = [2, 7, 4, 9, 6]

oddadd =0
evenadd = 0

for i in Example:
  if i%2 != 0:
    oddadd += i
  else:
    evenadd+=i


print(np.absolute(oddadd - evenadd))

4

In [21]:
import numpy as np
Array = [10, 25, 30, 15, 40]
Array2 = []
k = 20


for i in Array:
  if i > k:
    Array2.append(i)


print(sum(Array2)/len(Array2))

31.666666666666668

In [3]:
import pandas as pd

students = pd. DataFrame ( {
"Student_ID": [101, 102, 103, 104, 105, 106],
"Name": ["Amit","Priya","Rahul","Sneha","Karan", "Neha"],
"Python": [80, 95, 45, 70, 30, 88],
"SQL": [75,90,50,65,40,92],
"Statistics": [85,92, 40, 80, 35, 90],
"Attendance": [90,95,65, 80, 55, 98],
"Branch": ["CSE","IT","CSE","ECE","ME","IT"]
})
print(students)

   Student_ID   Name  Python  SQL  Statistics  Attendance Branch
0         101   Amit      80   75          85          90    CSE
1         102  Priya      95   90          92          95     IT
2         103  Rahul      45   50          40          65    CSE
3         104  Sneha      70   65          80          80    ECE
4         105  Karan      30   40          35          55     ME
5         106   Neha      88   92          90          98     IT

In [31]:
# Q1. Create a column Academic_year and assign value 2026 to each student


students["Academic_year"] = 2026

In [32]:
students

,Student_ID,Name,Python,SQL,Statistics,Attendance,Branch,Academic_year
0,101,Amit,80,75,85,90,CSE,2026
1,102,Priya,95,90,92,95,IT,2026
2,103,Rahul,45,50,40,65,CSE,2026
3,104,Sneha,70,65,80,80,ECE,2026
4,105,Karan,30,40,35,55,ME,2026
5,106,Neha,88,92,90,98,IT,2026

In [ ]:
# Q2. Assign a mentor to each student.

In [38]:
mentor = ["anish","manish","pranish","nish","shranish","shranish"]

In [39]:
students["mentor"]= mentor

In [40]:
students

,Student_ID,Name,Python,SQL,Statistics,Attendance,Branch,Academic_year,mentor
0,101,Amit,80,75,85,90,CSE,2026,anish
1,102,Priya,95,90,92,95,IT,2026,manish
2,103,Rahul,45,50,40,65,CSE,2026,pranish
3,104,Sneha,70,65,80,80,ECE,2026,nish
4,105,Karan,30,40,35,55,ME,2026,shranish
5,106,Neha,88,92,90,98,IT,2026,shranish

In [41]:
total_marks = students["Python"]+ students["SQL"]+  students["Statistics"]
students["total_marks"]= total_marks

In [42]:
students

,Student_ID,Name,Python,SQL,Statistics,Attendance,Branch,Academic_year,mentor,total_marks
0,101,Amit,80,75,85,90,CSE,2026,anish,240
1,102,Priya,95,90,92,95,IT,2026,manish,277
2,103,Rahul,45,50,40,65,CSE,2026,pranish,135
3,104,Sneha,70,65,80,80,ECE,2026,nish,215
4,105,Karan,30,40,35,55,ME,2026,shranish,105
5,106,Neha,88,92,90,98,IT,2026,shranish,270

In [43]:
import numpy as np
percentage_marks =np.round((students["total_marks"]/3),2)
students['percentage_marks']= percentage_marks

In [44]:
students

,Student_ID,Name,Python,SQL,Statistics,Attendance,Branch,Academic_year,mentor,total_marks,percentage_marks
0,101,Amit,80,75,85,90,CSE,2026,anish,240,80.00
1,102,Priya,95,90,92,95,IT,2026,manish,277,92.33
2,103,Rahul,45,50,40,65,CSE,2026,pranish,135,45.00
3,104,Sneha,70,65,80,80,ECE,2026,nish,215,71.67
4,105,Karan,30,40,35,55,ME,2026,shranish,105,35.00
5,106,Neha,88,92,90,98,IT,2026,shranish,270,90.00

In [ ]:
# avg marks for every student.

In [45]:
average_marks = np.average([students["Python"], students["SQL"], students["Statistics"]])

In [47]:
students["average_marks"] = average_marks

In [48]:
students

,Student_ID,Name,Python,SQL,Statistics,Attendance,Branch,Academic_year,mentor,total_marks,percentage_marks,average_marks
0,101,Amit,80,75,85,90,CSE,2026,anish,240,80.00,69.0
1,102,Priya,95,90,92,95,IT,2026,manish,277,92.33,69.0
2,103,Rahul,45,50,40,65,CSE,2026,pranish,135,45.00,69.0
3,104,Sneha,70,65,80,80,ECE,2026,nish,215,71.67,69.0
4,105,Karan,30,40,35,55,ME,2026,shranish,105,35.00,69.0
5,106,Neha,88,92,90,98,IT,2026,shranish,270,90.00,69.0

In [50]:
print(students[["Python","SQL","Statistics"]].mean())

Python        68.000000
SQL           68.666667
Statistics    70.333333
dtype: float64

In [51]:
print(students[["Python","SQL","Statistics"]].mean(axis=1))

0    80.000000
1    92.333333
2    45.000000
3    71.666667
4    35.000000
5    90.000000
dtype: float64

In [ ]:
# Which students scored better in Python than in SQL, and by how much?

In [65]:
condition= students[students["Python"]>students["SQL"]]

In [66]:
condition

,Student_ID,Name,Python,SQL,Statistics,Attendance,Branch,Academic_year,mentor,total_marks,percentage_marks,average_marks
0,101,Amit,80,75,85,90,CSE,2026,anish,240,80.00,69.0
1,102,Priya,95,90,92,95,IT,2026,manish,277,92.33,69.0
3,104,Sneha,70,65,80,80,ECE,2026,nish,215,71.67,69.0

In [67]:
condition["diffbetn"]= condition["Python"]-condition["SQL"]

/tmp/ipykernel_752/598044686.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  condition["diffbetn"]= condition["Python"]-condition["SQL"]

In [68]:
condition

,Student_ID,Name,Python,SQL,Statistics,Attendance,Branch,Academic_year,mentor,total_marks,percentage_marks,average_marks,diffbetn
0,101,Amit,80,75,85,90,CSE,2026,anish,240,80.00,69.0,5
1,102,Priya,95,90,92,95,IT,2026,manish,277,92.33,69.0,5
3,104,Sneha,70,65,80,80,ECE,2026,nish,215,71.67,69.0,5

In [69]:
# assign 5 grace marks for every students

In [6]:
students["Python"]+=10

In [7]:
students

   Student_ID   Name  Python  SQL  Statistics  Attendance Branch
0         101   Amit      95   75          85          90    CSE
1         102  Priya     110   90          92          95     IT
2         103  Rahul      60   50          40          65    CSE
3         104  Sneha      85   65          80          80    ECE
4         105  Karan      45   40          35          55     ME
5         106   Neha     103   92          90          98     IT

In [8]:
python2=(students["Python"]+5).clip(upper= 100)

In [9]:
python2

0    100
1    100
2     65
3     90
4     50
5    100
Name: Python, dtype: int64