<a href="https://colab.research.google.com/github/AnishShrestha09/pandas/blob/main/pandas9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Problem statement: Given an array containing positive and negative integers,
# find the element whose absolute value is smallest.
# If two elements are equally close to zero, choose the positive one.


Example: [-8, 3, -2,5, 2]
Output: 2

In [ ]:
import numpy as np

In [ ]:
Example =  [-8, 3, -2,5, 2]
smallest = float("inf")

for i in Example:
  if np.absolute(i) <smallesst:
    smallest = i

print(smallest)

NameError: name 'np' is not defined

In [1]:
import pandas as pd

products = pd.DataFrame({
"Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Webcam"],
"Category": ["Electronics", "Accessories", "Accessories",
"Electronics", "Accessories"],
"Price": [55000, 700, 1500, 12000, 2500],
"Stock": [10, 100, 50, 15, 25]
})

In [2]:
products

    Product     Category  Price  Stock
0    Laptop  Electronics  55000     10
1     Mouse  Accessories    700    100
2  Keyboard  Accessories   1500     50
3   Monitor  Electronics  12000     15
4    Webcam  Accessories   2500     25

In [4]:
# Products costing less than 2000

products[products["Price"]<2000]

    Product     Category  Price  Stock
1     Mouse  Accessories    700    100
2  Keyboard  Accessories   1500     50

In [5]:
# Products with fewer than 20 units in stock

products[products["Stock"]<20]

   Product     Category  Price  Stock
0   Laptop  Electronics  55000     10
3  Monitor  Electronics  12000     15

In [6]:
# Electronics only

products[products["Category"]=="Electronics"]

   Product     Category  Price  Stock
0   Laptop  Electronics  55000     10
3  Monitor  Electronics  12000     15

In [7]:
#Create a new column with the total inventory amount for each product.

products["total_inventory"] = products["Price"]* products["Stock"]
products

    Product     Category  Price  Stock  total_inventory
0    Laptop  Electronics  55000     10           550000
1     Mouse  Accessories    700    100            70000
2  Keyboard  Accessories   1500     50            75000
3   Monitor  Electronics  12000     15           180000
4    Webcam  Accessories   2500     25            62500

In [9]:
# Select product and stock columns for low-stock products(<20 20)

lowstock = products[products["Stock"]<20]
lowstock[["Product","Stock"]]

   Product  Stock
0   Laptop     10
3  Monitor     15

In [ ]:
# Check whether an array is strictly positive

# Problem statement: Determine whether every element in an array is greater than zero
# array containing zero or a negative value does not satisfy the condition.

In [12]:
Example =  [4, 8,-1,6]

In [14]:
negative = False
for i in Example:
  if i <=0:
    negative = True


print("Negative" if negative else "postive")

Negative

In [ ]:
# Find the longest .consecutive run of positive numbers

# Problem statement:
# Find the length of the longest contiguous .sequence containing only positive .numbers.
# Zero and.negative values break the sequence.

# Example: [2,3,-1, 4, 5, 6, 0, 8]
# Output: 3.

In [18]:
import numpy as np
Example = [2,3, 4, 5, 6, 8]
count = 0
counted = []

for i in Example:
  if i > 0:
    count +=1
  else:
    counted.append(count)
    count = 0
counted.append(count)



np.max(counted)

np.int64(6)

In [23]:
# Find the element closest to zero

# Problem statement: Given an array containing positive and negative integers,
# find the element whose absolute value is smallest.
# If two elements are equally close to zero, choose the positive one.

Example =  [-8, 3, -2, 5]

Output =  2

-9