<a href="https://colab.research.google.com/github/AnishShrestha09/pandas/blob/main/pandas3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Find the Index Where Left and Right Products Are Equal

# Problem statement: Find an index where the product of all elements
# to its left equals the product of all elements to its right.
# Exclude the element at that index from both products.
# Assume the array contains positive integers greater than zero.

In [ ]:
a = [4, 3,1, 5, 2, 6,1]

mid_indx = int(len(a)/2)
# print(mid_indx)
A =len(a)-2

while(A):
  mul1 = 1
  mul2 = 1

  for i in range(mid_indx):
    mul1 *= a[i]

  for j in range(mid_indx+1,len(a)):
    mul2 *= a[j]

    if(mul1 == mul2):
      print("found",mid_indx)
      flag = True

  if(flag == True):
    break

  mid_indx += 1

found 3
found 3

In [ ]:
# Answer Multiple Range-Sum Queries

# Problem statement: Given an array and several queries,
# each containing a starting index L and ending index R,
# calculate the sum of elements from index L to index R, inclusive.

# Example: Array [3, 5, 2, 8, 4]
# - Query L = 1, R = 3 - 15
# - Query L = 0, R = 2 - 10

In [ ]:
Arra = [3, 5, 2, 8, 4]
l = 0
r = 2
sum = 0
for i in range(l,r+1):
  sum += Arra[i]


print(sum)

10

In [ ]:
# Calculate the Prefix Sum Array

# Problem statement: Given an array,
# create a new array where each position contains the sum of
# all elements from index 0 to that position.

Example:[2, 4, 1, 5, 3]
Output: [15,13,9,8,3]

In [ ]:
Example = [2, 4, 1, 5, 3]
Output = []
sum = 0
for i in range(len(Example)) :
  sum  = 0
  # print(i)

  for j in range(i+1):

    sum +=Example[j]

  Output.append(sum)

print(Output)

[2, 6, 7, 12, 15]

In [ ]:
# Find the Longest Subarray with Equal Numbers of 0s and 1s

In [ ]:
# Find the Longest Subarray with Equal Numbers of 0s and 1s

# Problem statement: Given an array containing only 0 and 1,
# find the length of the longest contiguous subarray containing
# an equal number of zeros and ones.

In [ ]:
Example=[0, 1, 0, 0, 1, 1, 0,1]

count0 = 0
count1 = 0

for i in Example:
  if i == 0:
    count0 +=1

  else:
    count1 +=1

while(count0 != count1):

  if(count0 > count1):
    count0-=1
  else:
    count1-=1

print(count0+ count1)

8

In [ ]:
# Pandas
import pandas as pd
import numpy as np

In [ ]:
csv_data = """Student,Age,Marks, Branch
Amit,18,85,CSE
Priya, 19,92,ECE
Rahul, 18,76,IT
Sneha, 20,88,CSE
Karan, 19,67,ME"""

In [ ]:
with open("students.csv","w") as file:
  file.write(csv_data)

In [ ]:
# load the data from the existing file

In [ ]:
df = pd.read_csv("students.csv")

In [ ]:
df

  Student  Age  Marks  Branch
0    Amit   18     85     CSE
1   Priya   19     92     ECE
2   Rahul   18     76      IT
3   Sneha   20     88     CSE
4   Karan   19     67      ME

In [ ]:
df.shape

(5, 4)

In [ ]:
df.columns

Index(['Student', 'Age', 'Marks', ' Branch'], dtype='object')

In [ ]:
list(df.columns)

['Student', 'Age', 'Marks', ' Branch']

In [ ]:
# summary of table information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  5 non-null      object
 1   Age      5 non-null      int64
 2   Marks    5 non-null      int64
 3    Branch  5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [ ]:
#  find the min , max, avg of marks


print(df["Marks"].min())
print(df["Marks"].max())
print(df["Marks"].mean())

67
92
81.6

In [ ]:
# from google.colab import files

# uploaded = files.upload()

In [ ]:
import os
print(os.listdir())

['.config', 'students.csv', 'drive', 'sample_data']

In [ ]:
data = """Name,Age, City
Amit,20,Nagpur
Priya, 21, Puņe
Rahul,19,Mumbai"""

with open("people.csv","w") as file:
  file.write(data)


df2 = pd.read_csv("people.csv")
df2

    Name  Age    City
0   Amit   20  Nagpur
1  Priya   21    Puņe
2  Rahul   19  Mumbai

In [ ]:
# not for a comma seperated value
#  for example: ';'

In [ ]:
data = """Name; Age; City
Amit; 20; Nagpur
Priya; 21; Pune
Rahul;19;Mumbai"""

with open("people.csv","w") as file:
  file.write(data)


people = pd.read_csv("people.csv",sep=";")
people

    Name   Age     City
0   Amit    20   Nagpur
1  Priya    21     Pune
2  Rahul    19   Mumbai

In [ ]:
data = """Product |Price |Stock
Laptop|55000|10
Mouse |700 | 100
Keyboard| 1500 | 50"""

with open("products.csv","w") as file:
  file.write(data)

products = pd.read_csv("products.csv",sep="|")
products

   Product   Price   Stock
0    Laptop   55000     10
1    Mouse      700    100
2  Keyboard    1500     50

In [ ]:
data = """
Laptop|55000|10
Mouse |700 | 100
Keyboard| 1500 | 50"""

with open("products.csv","w") as file:
  file.write(data)

products = pd.read_csv("products.csv",sep="|")
products

     Laptop  55000   10
0    Mouse     700  100
1  Keyboard   1500   50

In [34]:
data = """
Laptop|55000|10
Mouse |700 | 100
Keyboard| 1500 | 50"""

with open("products.csv","w") as file:
  file.write(data)

products = pd.read_csv("products.csv",sep="|",header=None, names=["name","price","stock"])
products

       name  price  stock
0    Laptop  55000     10
1    Mouse     700    100
2  Keyboard   1500     50

In [35]:
#  rename the column of dataframe

products.columns = ["products","price","stock"]
products

   products  price  stock
0    Laptop  55000     10
1    Mouse     700    100
2  Keyboard   1500     50

In [54]:
data = """Student performance report
Generated by College ABC
Name, Marks,Branch
Amit,85,CSE
Priya,92,ECE
Rahul,76, IT"""

with open("studentresult.csv","w") as file:
  file.write(data)

products = pd.read_csv("studentresult.csv",skiprows=2)
products

    Name   Marks Branch
0   Amit      85    CSE
1  Priya      92    ECE
2  Rahul      76     IT

In [56]:
products["Branch"]

0    CSE
1    ECE
2     IT
Name: Branch, dtype: object

In [53]:
# load the specific cols only
data = """Name,Age,City
Amit,20,Nagpur
Priya, 21, Puņe
Rahul,19,Mumbai"""

with open("people.csv","w") as file:
  file.write(data)


df2 = pd.read_csv("people.csv",usecols=["City"])
df2

     City
0  Nagpur
1    Puņe
2  Mumbai

In [57]:
df2.head(3)

     City
0  Nagpur
1    Puņe
2  Mumbai

In [58]:
data = """Name,Age,City
Amit, 20,Nagpur
Priya, 21, Pune
Rahul, 19,Mumbai"""

with open("people.csv", "w") as file:
  file.write(data)

df = pd.read_csv("people.csv", nrows =2)
df

    Name  Age    City
0   Amit   20  Nagpur
1  Priya   21    Pune

In [59]:
#load only the name and age of the first student in df.

data = """Name,Age,City
Amit, 20,Nagpur
Priya, 21,Pune
Rahul,19,Mumbai"""

with open("people.csv", "w") as file:
  file.write(data)

people = pd.read_csv("people.csv",usecols=["Name","Age"],nrows=1)

people

   Name  Age
0  Amit   20

In [ ]:
# Find the Minimum Length Subarray with Sum at Least S

# Problem statement: Given an array of positive integers and a target S,
# find the minimum length of a contiguous subarray whose sum is at least S.
# Print 0 if no such subarray exists.